"""
Companion plotting/table script for refinement_demo.py's runtime sweep.

Renamed from plot_refinement_runtime_scaling.py when the xn/pace branch was
merged in: that name is taken by the Slurm-log-scraping N=2..100 plotter for
refinement_demo_stable.py (and is what plot_post_compile_runtime_filtered.py /
plot_unrefined_vs_refined_scaling.py refer to). This script is the CSV-based
one, and is the only producer of the LaTeX table.

Reads refinement_runtime_scaling.csv (written by refinement_demo.py's
run_for_order, one row per state-dimension N) and produces:
  - refinement_runtime_scaling.pdf   -- two-panel figure: compile time vs. N
                                         and run time vs. N (timeit-style
                                         average vs. single dispatched call)
  - refinement_runtime_scaling_table.tex -- a booktabs LaTeX table with the
                                         same data, ready to \\input{} into a
                                         report (matches go2_system_report.tex's
                                         booktabs style)

Does not run any JAX code itself -- run refinement_demo.py first to
(re)generate the CSV, then run this script to plot/tabulate it.
"""

import csv
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent
if str(_HERE) not in sys.path:
    sys.path.insert(0, str(_HERE))

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

from refinement_demo import RUNTIME_CSV_PATH

OUT_PDF = _HERE / "refinement_runtime_scaling.pdf"
OUT_TEX = _HERE / "refinement_runtime_scaling_table.tex"

# Categorical slots 1/2 from the project's validated palette (light mode):
# blue for a single-series panel, blue+orange (fixed order) for the
# two-series run-time panel.
_COLOR_COMPILE = "#2a78d6"      # slot 1 (blue)
_COLOR_RUN_AVG = "#2a78d6"      # slot 1 (blue)
_COLOR_RUN_SINGLE = "#eb6834"   # slot 2 (orange)

plt.rcParams.update({
    'font.family': 'serif',
    'font.serif': ['Computer Modern'],
    'text.usetex': False,
})


def load_rows(csv_path: Path = RUNTIME_CSV_PATH):
    if not csv_path.exists():
        raise FileNotFoundError(
            f"{csv_path} not found -- run refinement_demo.py first to generate it."
        )
    with open(csv_path, newline="") as f:
        rows = list(csv.DictReader(f))
    for row in rows:
        for key in ("N", "run_time_repeats", "num_restarts", "num_iters", "num_steps"):
            row[key] = int(float(row[key]))
        for key in ("compile_time_ms", "run_time_single_ms", "run_time_avg_ms",
                    "unrefined_loss", "refined_loss"):
            row[key] = float(row[key])
    rows.sort(key=lambda r: r["N"])
    return rows


def make_plot(rows, out_path: Path = OUT_PDF):
    Ns = [r["N"] for r in rows]
    compile_s = [r["compile_time_ms"] / 1e3 for r in rows]
    run_avg_ms = [r["run_time_avg_ms"] for r in rows]
    run_single_ms = [r["run_time_single_ms"] for r in rows]

    # Two panels, not a dual y-axis: compile time (seconds) and run time (ms)
    # differ by ~3 orders of magnitude and are different quantities, so they
    # get separate axes rather than a shared/twin one.
    fig, (ax_compile, ax_run) = plt.subplots(1, 2, figsize=(11, 4.2))

    ax_compile.plot(Ns, compile_s, color=_COLOR_COMPILE, linewidth=2,
                     marker='o', markersize=5)
    ax_compile.set_xlabel("State dimension N")
    ax_compile.set_ylabel("Compile time (s)")
    ax_compile.set_title("JIT compile time vs. N")
    ax_compile.grid(True, color="0.85", linewidth=0.8)
    for spine in ("top", "right"):
        ax_compile.spines[spine].set_visible(False)

    repeats = rows[0]["run_time_repeats"] if rows else "?"
    ax_run.plot(Ns, run_avg_ms, color=_COLOR_RUN_AVG, linewidth=2,
                marker='o', markersize=5, label=f"avg of {repeats} calls")
    ax_run.plot(Ns, run_single_ms, color=_COLOR_RUN_SINGLE, linewidth=2,
                marker='o', markersize=5, label="single dispatched call")
    ax_run.set_xlabel("State dimension N")
    ax_run.set_ylabel("Run time (ms)")
    ax_run.set_title("Post-compilation run time vs. N")
    ax_run.grid(True, color="0.85", linewidth=0.8)
    ax_run.legend(frameon=False)
    for spine in ("top", "right"):
        ax_run.spines[spine].set_visible(False)

    fig.suptitle("Refined multistart optimizer -- runtime scaling with N")
    fig.tight_layout()
    fig.savefig(out_path, bbox_inches='tight')
    plt.close(fig)
    return out_path


def make_latex_table(rows, out_path: Path = OUT_TEX):
    lines = [
        r"% Auto-generated by plot_refinement_runtime_table.py -- do not edit by hand.",
        r"\begin{table}[htbp]",
        r"  \centering",
        r"  \begin{tabular}{rrrrrr}",
        r"    \toprule",
        r"    $N$ & Compile (s) & Run avg (ms) & Run 1x (ms) & Unrefined loss & Refined loss \\",
        r"    \midrule",
    ]
    for r in rows:
        lines.append(
            f"    {r['N']} & {r['compile_time_ms'] / 1e3:.2f} & "
            f"{r['run_time_avg_ms']:.3f} & {r['run_time_single_ms']:.3f} & "
            f"{r['unrefined_loss']:.4f} & {r['refined_loss']:.4f} \\\\"
        )
    repeats = rows[0]["run_time_repeats"] if rows else "?"
    lines += [
        r"    \bottomrule",
        r"  \end{tabular}",
        r"  \caption{Refined multistart optimizer compile/run time vs.\ state "
        f"dimension $N$. Run avg is the mean of {repeats} back-to-back calls "
        r"on the compiled function; run 1x is a single dispatched call.}",
        r"  \label{tab:refinement-runtime-scaling}",
        r"\end{table}",
    ]
    out_path.write_text("\n".join(lines) + "\n")
    return out_path


if __name__ == "__main__":
    rows = load_rows()
    print(f"Loaded {len(rows)} rows from {RUNTIME_CSV_PATH}")

    pdf_path = make_plot(rows)
    print(f"Wrote plot: {pdf_path}")

    tex_path = make_latex_table(rows)
    print(f"Wrote LaTeX table: {tex_path}")
